package com.github.sugayamidori.viaseguraapi.controller.docs;

import com.github.sugayamidori.viaseguraapi.controller.dto.ErrorResponse;
import com.github.sugayamidori.viaseguraapi.controller.dto.PredictionDTO;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.media.ArraySchema;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.tags.Tag;
import org.springframework.data.domain.Page;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.RequestParam;

import java.math.BigDecimal;

@Tag(name = "Prediction", description = "Endpoints for querying accident predictions based on machine learning models")
public interface PredictionControllerDocs {

    @Operation(
            summary = "Search accident predictions with filters",
            description = """
                    Performs paginated search of accident predictions generated by ML models.
                    
                    **Available filters:**
                    - H3 cell identifier (specific geographic location)
                    - Week start date (ISO 8601 format)
                    - Minimum predicted accidents threshold
                    
                    **Use cases:**
                    - Risk assessment for specific areas
                    - Weekly accident forecasting
                    - Resource allocation planning
                    - Identifying high-risk zones
                    
                    **Notes:**
                    - All filters are optional and can be combined
                    - Default pagination returns 300 records per page
                    - Predictions are based on historical accident data and patterns
                    - Week start date should be in ISO format (YYYY-MM-DD)
                    """,
            responses = {
                    @ApiResponse(
                            responseCode = "200",
                            description = "Search completed successfully",
                            content = @Content(
                                    mediaType = MediaType.APPLICATION_JSON_VALUE,
                                    array = @ArraySchema(schema = @Schema(implementation = PredictionDTO.class))
                            )
                    ),
                    @ApiResponse(
                            responseCode = "400",
                            description = "Invalid parameters (e.g., malformed date, invalid H3 cell, negative values)",
                            content = @Content(
                                    mediaType = MediaType.APPLICATION_JSON_VALUE,
                                    schema = @Schema(implementation = ErrorResponse.class)
                            )
                    ),
                    @ApiResponse(
                            responseCode = "401",
                            description = "User not authenticated - missing or invalid token",
                            content = @Content(
                                    mediaType = MediaType.APPLICATION_JSON_VALUE,
                                    schema = @Schema(implementation = ErrorResponse.class)
                            )
                    ),
                    @ApiResponse(
                            responseCode = "403",
                            description = "Access denied - user without permission to view predictions",
                            content = @Content(
                                    mediaType = MediaType.APPLICATION_JSON_VALUE,
                                    schema = @Schema(implementation = ErrorResponse.class)
                            )
                    ),
                    @ApiResponse(
                            responseCode = "404",
                            description = "No predictions found matching the specified criteria",
                            content = @Content(
                                    mediaType = MediaType.APPLICATION_JSON_VALUE,
                                    schema = @Schema(implementation = ErrorResponse.class)
                            )
                    ),
                    @ApiResponse(
                            responseCode = "500",
                            description = "Internal server error",
                            content = @Content(
                                    mediaType = MediaType.APPLICATION_JSON_VALUE,
                                    schema = @Schema(implementation = ErrorResponse.class)
                            )
                    )
            }
    )
    ResponseEntity<Page<PredictionDTO>> search(
            @Parameter(
                    description = "H3 cell identifier for filtering predictions by geographic location",
                    example = "8981839b527ffff"
            )
            @RequestParam(value = "h3Cell", required = false) String h3Cell,

            @Parameter(
                    description = "Start date of the prediction week in ISO 8601 format (YYYY-MM-DD)",
                    example = "2026-01-05"
            )
            @RequestParam(value = "weekStart", required = false) String weekStart,

            @Parameter(
                    description = "Probability to accident",
                    example = "1.2181633946136847",
                    schema = @Schema(minimum = "0")
            )
            @RequestParam(value = "predictedAccidents", required = false) BigDecimal predictedAccidents,

            @Parameter(
                    description = "Page number (starts at 0)",
                    example = "0",
                    schema = @Schema(minimum = "0")
            )
            @RequestParam(value = "page", defaultValue = "0") Integer page,

            @Parameter(
                    description = "Number of records per page",
                    example = "300",
                    schema = @Schema(minimum = "1", maximum = "1000")
            )
            @RequestParam(value = "pageSize", defaultValue = "300") Integer pageSize
    );
}